TITLE BetterRandomRange Procedure			(BRRProc.asm)
; ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
; Description:	 Generates an integer between M and N-1 and displays it.
; Author:		 Marrusian
; Creation Date: 04/08/2014
; Revisions:	 N/A
; Date:			 N/A
; ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
includelib	D:\masm32\lib\Irvine32.lib
				.386
				.MODEL flat,stdcall
				.STACK 100h
Randomize		PROTO
RandomRange		PROTO
WriteInt		PROTO
WriteChar		PROTO
WriteString		PROTO
ExitProcess		PROTO dwExitCode:DWORD
; ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
				.DATA
RANDOM_COUNT = 50
TAB			 = 9

rdmErr			BYTE "ERROR: The lower bound (EBX) can't be greater than the upper bound (EAX)",0
; ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
				.CODE
main			PROC
; Calls: Randomize, BetterRdmRange, DisplayInt.
				mov ecx,RANDOM_COUNT
				mov ebx,-200
				mov eax,-50
				call Randomize
for01:			call BetterRdmRange
				call DisplayInt
				loop for01
endfor01:		nop				
				INVOKE ExitProcess,0
main			ENDP

; ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
BetterRdmRange  PROC USES eax
;
; Description:	Generates an integer between M and N-1.
;				Provides an error-check for the bounds and sets the return
;				value to -1 if bounds are not valid.
; Receives:		EBX = the lower bound (M)
;				EAX = the upper bound (N)
; Returns:		EDX = the random integer
; Calls:		RandomRange, WriteString				(Irvine32.lib)
; ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
if01:			cmp eax,ebx			; if eax >= ebx
				jl else01
then01:			nop
 if02:			cmp eax,0			; if eax >= 0
				jl else02
 then02:		nop
  if03:			cmp ebx,0			; if ebx >= 0
				jl else03
  then03:		sub eax,ebx
				call RandomRange
				add eax,ebx
				jmp endif03
  else03:		sub eax,ebx
				call RandomRange
				add eax,ebx
  endif03:		jmp endif02
 else02:		sub eax,ebx
 				call RandomRange
				add eax,ebx		
 endif02:		mov edx,eax
				jmp endif01
else01:			mov edx,OFFSET rdmErr
				call WriteString
				mov edx,-1
endif01:		nop
				ret
BetterRdmRange	ENDP

; ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
DisplayInt		PROC USES eax
;
; Description: Display a 32-bit integer generated by the BetterRdmRange procedure.
; Receives:	   EDX = the integer
; Returns:	   N/A
; Calls:	   WriteInt, WriteChar								(Irvine32.lib)
; ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
				mov eax,edx
				call WriteInt
				mov al,TAB
				call WriteChar
				ret
DisplayInt		ENDP

				END main